---
- name: create user
  user:
    name: "{{ username }}"
    password: "{{ lookup('password','credentials/' + inventory_hostname + '/user_' +  username  + '_password length=32 chars=hexdigits') |password_hash('sha512') }}"
    update_password: on_create
    state: present
